Eric
revaturelabs/caliber-trainer-report-front pull request #133
Opened 2021-01-15 21:02 UTC by Eric-Ro

Updated imports in app-routing.module.ts to accommodate new file names.

2021-01-15 22:01 UTC, snicholes requested changes

2021-01-15 22:01 UTC, snicholes commented on CaliberTrainerReport/src/app/services/batch-status-by-skill-cat.service.ts
> +  // // X-axis variables...
remove commented out code

2021-01-15 22:01 UTC, snicholes commented on CaliberTrainerReport/src/app/services/scores-by-category-all-batches.service.ts
> +  // getXData(){
remove commented out code

2021-01-19 17:33 UTC, Eric-Ro commented
I've applied the requested changes!

2021-01-19 17:34 UTC, merged